-- Bilingual workshop votes table (for /#/workshopvote and /#/voteresults)
-- Run this in Supabase SQL Editor

CREATE TABLE "WorkshopVotesBilingual" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE "WorkshopVotesBilingual" ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read votes
CREATE POLICY "Allow select for everyone" ON "WorkshopVotesBilingual"
  FOR SELECT USING (true);

-- Allow anyone to insert votes
CREATE POLICY "Allow insert for everyone" ON "WorkshopVotesBilingual"
  FOR INSERT WITH CHECK (true);

-- Allow anyone to delete votes (for reset)
CREATE POLICY "Allow delete for everyone" ON "WorkshopVotesBilingual"
  FOR DELETE USING (true);

-- Enable realtime (optional)
ALTER PUBLICATION supabase_realtime ADD TABLE "WorkshopVotesBilingual";
